llvm 12

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
 set -e
+set -x
 set -o pipefail
 set -u
+# https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-x86_64-apple-darwin.tar.xz
 
-# https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-apple-darwin.tar.xz
-LLVM_VERSION=11.0.0
-LLVM_HASH=827debc34e797b65f60fb27de4078ba9a4c23c321f3d3b42f7c6be31a6d94dcd
+LLVM_VERSION=12.0.0
 LLVM_CONFIG=${LLVM_CONFIG:-llvm-config}
 
 command -v "${LLVM_CONFIG}" >/dev/null 2>&1 || {
@@ -19,8 +19,6 @@ command -v "${LLVM_CONFIG}" >/dev/null 2>&1 || {
             echo "Downloading ${URL}..."
             curl --retry 3 -# -S -L "${URL}" -o "${FILE}.tmp" && mv "${FILE}.tmp" "${FILE}"
         fi
-        echo -n "Checking file... "
-        echo "${LLVM_HASH}  ${FILE}" | shasum -a 512256 -c
         rm -rf "${PREFIX}"
         mkdir -p "${PREFIX}"
         echo -n "Unpacking archive... "
@@ -32,12 +30,15 @@ command -v "${LLVM_CONFIG}" >/dev/null 2>&1 || {
 
 PREFIX="$("${LLVM_CONFIG}" --prefix)"
 case "${PREFIX}" in
-  *\ *) (>&2 echo "Error: Path to LLVM may not contain spaces: '${PREFIX}'"); exit 1 ;;
+*\ *)
+    (echo >&2 "Error: Path to LLVM may not contain spaces: '${PREFIX}'")
+    exit 1
+    ;;
 esac
 
-echo "// Do not modify this file. Instead, rerun ./configure" > config.xcconfig
-echo "LLVM_LIBDIR=$(${LLVM_CONFIG} --libdir)" >> config.xcconfig
-echo "LLVM_CXXFLAGS=$(${LLVM_CONFIG} --cxxflags)" >> config.xcconfig
+echo "// Do not modify this file. Instead, rerun ./configure" >config.xcconfig
+echo "LLVM_LIBDIR=$(${LLVM_CONFIG} --libdir)" >>config.xcconfig
+echo "LLVM_CXXFLAGS=$(${LLVM_CONFIG} --cxxflags)" >>config.xcconfig
 
 echo "Wrote config.xcconfig."
 
